// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package sms_do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SmsSendLog is the golang structure of table sms_send_log for DAO operations like Where/Data.
type SmsSendLog struct {
	g.Meta      `orm:"table:sms_send_log, do:true"`
	Id          interface{} // ID
	AppId       interface{} // 应用ID
	BusinessNo  interface{} // 业务编号
	Fee         interface{} // 条数
	PhoneNumber interface{} // 发送手机号
	Message     interface{} // 接口响应消息
	Code        interface{} // 接口响应状态码
	Content     interface{} // 发送内容
	Remark      interface{} // 备注
	UnionMainId interface{} // 所属主体id
	Form        interface{} // 短信来源
	Type        interface{} // 短信类型：1验证、2通知、4业务、8推广
	Status      interface{} // 网关发送状态：0失败、1成功
	MetaData    interface{} // 网关返回元数据
	SignName    interface{} // 签名名称
	CreatedAt   *gtime.Time //
}
