// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sms_dao

import (
	"github.com/kysion/base-library/utility/daoctl/dao_interface"
	"github.com/kysion/sms-library/sms_model/sms_dao/internal"
)

type SmsServiceProviderConfig = dao_interface.TIDao[internal.SmsServiceProviderConfigColumns]

func NewSmsServiceProviderConfig(dao ...dao_interface.IDao) SmsServiceProviderConfig {
	return (SmsServiceProviderConfig)(internal.NewSmsServiceProviderConfigDao(dao...))
}
