// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package sms_dao

import (
	"github.com/kysion/base-library/utility/daoctl/dao_interface"
	"github.com/kysion/sms-library/sms_model/sms_dao/internal"
)

type SmsBusinessConfigDao = dao_interface.TIDao[internal.SmsBusinessConfigColumns]

func NewSmsBusinessConfig(dao ...dao_interface.IDao) SmsBusinessConfigDao {
	return (SmsBusinessConfigDao)(internal.NewSmsBusinessConfigDao(dao...))
}

var (
	SmsBusinessConfig = NewSmsBusinessConfig()
)
