// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "github.com/kysion/sms-library/internal/logic/sms"
	_ "github.com/kysion/sms-library/internal/logic/sms_aliyun"
	_ "github.com/kysion/sms-library/internal/logic/sms_qyxs"
	_ "github.com/kysion/sms-library/internal/logic/sms_tencent"
)
