// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/kysion/base-library/utility/daoctl"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SmsBusinessConfigDao is the data access object for table sms_business_config.
type SmsBusinessConfigDao struct {
	dao_interface.IDao
	table       string                   // table is the underlying table name of the DAO.
	group       string                   // group is the database configuration group name of current DAO.
	columns     SmsBusinessConfigColumns // columns contains all the column names of Table for convenient usage.
	daoConfig   *dao_interface.DaoConfig
	ignoreCache bool
	exWhereArr  []string
}

// SmsBusinessConfigColumns defines and stores column names for table sms_business_config.
type SmsBusinessConfigColumns struct {
	Id           string // ID
	AppId        string // 应用ID
	BusinessName string // 业务名称
	BusinessNo   string // 业务编号
	TemplateCode string // 模版Code
	BusinessDesc string // 业务说明
	Remark       string // 备注
	Status       string // 状态: 0禁用 1正常
	UnionMainId  string // 所属主体id
	CreatedAt    string //
	UpdatedAt    string //
	DeletedAt    string //
}

// smsBusinessConfigColumns holds the columns for table sms_business_config.
var smsBusinessConfigColumns = SmsBusinessConfigColumns{
	Id:           "id",
	AppId:        "app_id",
	BusinessName: "business_name",
	BusinessNo:   "business_no",
	TemplateCode: "template_code",
	BusinessDesc: "business_desc",
	Remark:       "remark",
	Status:       "status",
	UnionMainId:  "union_main_id",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
	DeletedAt:    "deleted_at",
}

// NewSmsBusinessConfigDao creates and returns a new DAO object for table data access.
func NewSmsBusinessConfigDao(proxy ...dao_interface.IDao) *SmsBusinessConfigDao {
	var dao *SmsBusinessConfigDao
	if len(proxy) > 0 {
		dao = &SmsBusinessConfigDao{
			group:       proxy[0].Group(),
			table:       proxy[0].Table(),
			columns:     smsBusinessConfigColumns,
			daoConfig:   proxy[0].DaoConfig(context.Background()),
			IDao:        proxy[0].DaoConfig(context.Background()).Dao,
			ignoreCache: proxy[0].DaoConfig(context.Background()).IsIgnoreCache(),
			exWhereArr:  proxy[0].DaoConfig(context.Background()).Dao.GetExtWhereKeys(),
		}

		return dao
	}

	return &SmsBusinessConfigDao{
		group:   "default",
		table:   "sms_business_config",
		columns: smsBusinessConfigColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SmsBusinessConfigDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SmsBusinessConfigDao) Table() string {
	return dao.table
}

// Group returns the configuration group name of database of current dao.
func (dao *SmsBusinessConfigDao) Group() string {
	return dao.group
}

// Columns returns all column names of current dao.
func (dao *SmsBusinessConfigDao) Columns() SmsBusinessConfigColumns {
	return dao.columns
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SmsBusinessConfigDao) Ctx(ctx context.Context, cacheOption ...*gdb.CacheOption) *gdb.Model {
	return dao.DaoConfig(ctx, cacheOption...).Model
}

func (dao *SmsBusinessConfigDao) DaoConfig(ctx context.Context, cacheOption ...*gdb.CacheOption) *dao_interface.DaoConfig {
	//if dao.daoConfig != nil && len(dao.exWhereArr) == 0 {
	//	return dao.daoConfig
	//}

	var daoConfig = daoctl.NewDaoConfig(ctx, dao, cacheOption...)
	dao.daoConfig = &daoConfig

	if len(dao.exWhereArr) > 0 {
		daoConfig.IgnoreExtModel(dao.exWhereArr...)
		dao.exWhereArr = []string{}

	}

	if dao.ignoreCache {
		daoConfig.IgnoreCache()
	}

	return dao.daoConfig
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SmsBusinessConfigDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}

func (dao *SmsBusinessConfigDao) GetExtWhereKeys() []string {
	return dao.exWhereArr
}

func (dao *SmsBusinessConfigDao) IsIgnoreCache() bool {
	return dao.ignoreCache
}

func (dao *SmsBusinessConfigDao) IgnoreCache() dao_interface.IDao {
	dao.ignoreCache = true
	return dao
}
func (dao *SmsBusinessConfigDao) IgnoreExtModel(whereKey ...string) dao_interface.IDao {
	dao.exWhereArr = append(dao.exWhereArr, whereKey...)
	return dao
}
