// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package sms_entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SmsTemplateConfig is the golang structure for table sms_template_config.
type SmsTemplateConfig struct {
	Id                     int64       `json:"id"                     orm:"id"                        description:"ID"`
	TemplateCode           string      `json:"templateCode"           orm:"template_code"             description:"模版Code"`
	TemplateName           string      `json:"templateName"           orm:"template_name"             description:"模版名称"`
	TemplateContent        string      `json:"templateContent"        orm:"template_content"          description:"模版内容"`
	ThirdPartyTemplateCode string      `json:"thirdPartyTemplateCode" orm:"third_party_template_code" description:"第三方模版Code"`
	ProviderNo             string      `json:"providerNo"             orm:"provider_no"               description:"渠道商编号"`
	Remark                 string      `json:"remark"                 orm:"remark"                    description:"备注"`
	Status                 int         `json:"status"                 orm:"status"                    description:"状态: 0禁用 1正常"`
	AuditUserId            int64       `json:"auditUserId"            orm:"audit_user_id"             description:"审核者UserID 审核者UserID"`
	AuditReplyMsg          string      `json:"auditReplyMsg"          orm:"audit_reply_msg"           description:"审核回复，仅审核不通过时才有值"`
	AuditAt                *gtime.Time `json:"auditAt"                orm:"audit_at"                  description:"审核时间"`
	ExtJson                string      `json:"extJson"                orm:"ext_json"                  description:"拓展字段"`
	UnionMainId            int64       `json:"unionMainId"            orm:"union_main_id"             description:"关联主体ID"`
	SignName               string      `json:"signName"               orm:"sign_name"                 description:"签名名称"`
	CreatedAt              *gtime.Time `json:"createdAt"              orm:"created_at"                description:""`
	UpdatedAt              *gtime.Time `json:"updatedAt"              orm:"updated_at"                description:""`
	DeletedAt              *gtime.Time `json:"deletedAt"              orm:"deleted_at"                description:""`
	Type                   int         `json:"type"                   orm:"type"                      description:"业务场景类型：1注册，2登录，4找回用户名/修改用户名，8找回密码/重置密码，16设置手机号码，32设置邮箱，64忘记用户名&密码"`
}
