// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package sms_entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SmsBusinessConfig is the golang structure for table sms_business_config.
type SmsBusinessConfig struct {
	Id           int64       `json:"id"           description:"ID"`
	AppId        string      `json:"appId"        description:"应用ID"`
	BusinessName string      `json:"businessName" description:"业务名称"`
	BusinessNo   string      `json:"businessNo"   description:"业务编号"`
	TemplateCode string      `json:"templateCode" description:"模版Code"`
	BusinessDesc string      `json:"businessDesc" description:"业务说明"`
	Remark       string      `json:"remark"       description:"备注"`
	Status       int         `json:"status"       description:"状态: 0禁用 1正常"`
	UnionMainId  int64       `json:"unionMainId"  description:"所属主体id"`
	CreatedAt    *gtime.Time `json:"createdAt"    description:""`
	UpdatedAt    *gtime.Time `json:"updatedAt"    description:""`
	DeletedAt    *gtime.Time `json:"deletedAt"    description:""`
}
