name: Continuous Integration

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]

jobs:
    test:
        name: Unit Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: '>=1.24.0'
                  cache: true

            - name: Run tests
              run: go test -v ./... -coverprofile=coverage.txt -covermode=atomic

            - name: Upload coverage report
              uses: codecov/codecov-action@v4
              with:
                  file: ./coverage.txt
                  fail_ci_if_error: false
                  token: ${{ secrets.CODECOV_TOKEN }}
