name: Continuous Integration

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

jobs:
    lint:
        name: Lint Code
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: '>=1.21.0'
                  cache: true

            - name: Install golangci-lint
              run: |
                  curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2
                  golangci-lint --version

            - name: Run golangci-lint
              run: golangci-lint run --timeout=5m

    test:
        name: Test Coverage
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: '>=1.24.0'
                  cache: true

            - name: Run tests with coverage
              run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

            - name: Upload coverage report to Codecov
              uses: codecov/codecov-action@v3
              with:
                  file: ./coverage.txt
                  flags: unittests
                  fail_ci_if_error: false

    security:
        name: Security Scan
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: '>=1.24.0'
                  cache: true

            - name: Run Gosec Security Scanner
              uses: securego/gosec@v2
              with:
                  args: '-no-fail -fmt sarif -out results.sarif ./...'

            - name: Upload SARIF file
              uses: github/codeql-action/upload-sarif@v2
              with:
                  sarif_file: results.sarif
