name: Release Go Module

on:
    push:
        branches:
            - main
    pull_request:
        types:
            - closed
        branches:
            - main
    workflow_dispatch:
        inputs:
            version_type:
                description: '版本更新类型 (patch, minor, major)'
                required: true
                default: 'patch'
                type: choice
                options:
                    - patch
                    - minor
                    - major

jobs:
    verify:
        name: Verify Code
        runs-on: ubuntu-latest
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch'
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: '>=1.24.0'
                  cache: true

            - name: Verify dependencies
              run: go mod verify

            - name: Run tests
              run: go test -v ./...

    release:
        name: Create Release
        needs: verify
        runs-on: ubuntu-latest
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch'
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  persist-credentials: false

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: '>=1.24.0'
                  cache: true

            - name: Go mod tidy
              run: go mod tidy

            # 手动版本更新处理（用于workflow_dispatch触发时）
            - name: Get latest tag for manual release
              if: github.event_name == 'workflow_dispatch'
              id: latest_tag
              run: |
                  echo "LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo 'v0.0.0')" >> $GITHUB_ENV
                  echo "Current latest tag: ${{ env.LATEST_TAG }}"

            - name: Determine new version for manual release
              if: github.event_name == 'workflow_dispatch'
              id: new_version
              run: |
                  LATEST_VERSION=${LATEST_TAG#v}
                  IFS='.' read -r -a VERSION_PARTS <<< "$LATEST_VERSION"
                  MAJOR=${VERSION_PARTS[0]:-0}
                  MINOR=${VERSION_PARTS[1]:-0}
                  PATCH=${VERSION_PARTS[2]:-0}

                  # 根据输入或默认更新相应的版本号
                  VERSION_TYPE="${{ github.event.inputs.version_type }}"

                  if [ "$VERSION_TYPE" = "major" ]; then
                    MAJOR=$((MAJOR+1))
                    MINOR=0
                    PATCH=0
                  elif [ "$VERSION_TYPE" = "minor" ]; then
                    MINOR=$((MINOR+1))
                    PATCH=0
                  else
                    PATCH=$((PATCH+1))
                  fi

                  NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
                  echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
                  echo "New version will be: $NEW_VERSION (type: $VERSION_TYPE)"

            # 使用conventional-changelog生成分类的变更日志（用于workflow_dispatch触发时）
            - name: Setup Node.js for manual release
              if: github.event_name == 'workflow_dispatch'
              uses: actions/setup-node@v3
              with:
                  node-version: '20'

            - name: Install conventional-changelog-cli for manual release
              if: github.event_name == 'workflow_dispatch'
              run: npm install -g conventional-changelog-cli

            - name: Generate classified changelog for manual release
              if: github.event_name == 'workflow_dispatch'
              run: |
                  conventional-changelog -p angular -i CHANGELOG.md -s -r 0
                  echo "# 版本 ${{ env.NEW_VERSION }}" > RELEASE_NOTES.md
                  echo "" >> RELEASE_NOTES.md
                  echo "发布日期: $(date +"%Y-%m-%d")" >> RELEASE_NOTES.md
                  echo "" >> RELEASE_NOTES.md
                  conventional-changelog -p angular -r 2 >> RELEASE_NOTES.md

            # 创建手动发布
            - name: Create manual release
              if: github.event_name == 'workflow_dispatch'
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ env.NEW_VERSION }}
                  name: Release ${{ env.NEW_VERSION }}
                  body_path: RELEASE_NOTES.md
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            # 自动语义化发布（用于push或PR合并触发时）
            - name: Setup Node.js for semantic release
              if: github.event_name != 'workflow_dispatch'
              uses: actions/setup-node@v3
              with:
                  node-version: '20'

            - name: Install semantic-release dependencies
              if: github.event_name != 'workflow_dispatch'
              run: |
                  npm install -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github

            - name: Semantic Release
              if: github.event_name != 'workflow_dispatch'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npx semantic-release

            # 提交go.mod和go.sum的更改
            - name: Commit and push changes
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  if git diff --quiet --exit-code go.mod go.sum; then
                    echo "No changes to commit"
                  else
                    git add go.mod go.sum
                    VERSION="${{ env.NEW_VERSION || 'latest' }}"
                    git commit -m "chore(deps): 更新依赖版本 for $VERSION"
                    git push
                  fi
